[tool.poetry]
name = "nyt"
version = "0.2.4"
description = "Stop wasting time on YouTube"
authors = ["thefr0gg"]
license = "GPL-3.0"
readme = "README.md"
packages = [
    {include = "nyt"}
]

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
yt-dlp = ">=2024.5.27,<2027.0.0"
fastapi = ">=0.111,<0.142"
uvicorn = ">=0.30,<0.54"
loguru = "^0.7.0"
requests = "^2.31.0"
orjson = "^3.9"

[tool.poetry.plugins."console_scripts"]
nyt = "nyt:cli.run"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
